name: Deploy Blog

on:
  release: 
    types: ["published"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build
      run: |
        set -euxo pipefail
        nix build
        mkdir -p .build
        cp -r result/* .build/.
        
    - name: Deploy
      uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
        NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub Actions"
        build_directory: .build
        install_command: "echo Skipping dependency install"
        build_command: "echo Skipping build"